### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by chandlerbing65nm** [csuhan/s2anet#122]
I tried running the test.py with --eval bbox 
```
python tools/test.py configs/rotated_iou/cascade_s2anet_2s_r50_fpn_1x_dota_iouloss.py work_dirs/cascade_s2anet_2s_r50_fpn_1x_dota_iouloss/epoch_9.pth --out work_dirs/cascade_s2anet_2s_r50_fpn_1x_dota_iouloss/results.pkl --eval bbox
```

But I encountered an error:
```
Traceback (most recent call last):
  File "tools/test.py", line 236, in <module>
    main()  File "tools/test.py", line 220, in main
    eval_kwargs = cfg.get('evaluation', {}).copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by csuhan** [comment]
I checked again and it still works.
Add a breakpoint before `line 220` to see if the key `evaluation` exists in your config file.
