### ISSUE TITLE
OSError:  work_dirs/epoch_12.pth is not a checkpoint file

### ISSUE THREAD

**Issue by rohansig** [csuhan/s2anet#131]
I trained the model on dota, but when I try to test it it throws this error.

Traceback (most recent call last):
  File "tools/test.py", line 236, in <module>
    main()
  File "tools/test.py", line 181, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 171, in load_checkpoint
    raise IOError('{} is not a checkpoint file'.format(filename))
OSError:  work_dirs/epoch_12.pth is not a checkpoint file

**Comment by csuhan** [comment]
Please check if `work_dirs/epoch_12.pth` exists.

**Comment by rohansig** [comment]
yes it exists triple checked :P

I myself trained the model, training was done successfully. I am not sure why its getting stuck while testing.

**Comment by csuhan** [comment]
You can download and try our pretrained one.
I guess there is something wrong with your trained model.

You can try to load it mamally `model = torch.load('your_model_path')` to see if it works.
