### ISSUE TITLE
RuntimeError: expected device cuda:1 but got device cuda:0

### ISSUE THREAD

**Issue by Sairam13001** [csuhan/s2anet#136]
Hai sir, 

I installed s2anet successfully with pytorch 1.3.1 and cuda 10.0.

gcc --version is: 7.5.0  

When I ran train.py using 4 gpus, I got the following error:

Traceback (most recent call last):
  File "tools/train.py", line 118, in <module>
    main()
  File "tools/train.py", line 114, in main
    logger=logger)
  File "/home/ai20resch13001/s2anet-b/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/ai20resch13001/s2anet-b/mmdet/apis/train.py", line 232, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/ai20resch13001/s2anet-b/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ai20resch13001/s2anet-b/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/ai20resch13001/s2anet-b/mmdet/models/detectors/base.py", line 100, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/ai20resch13001/s2anet-b/mmdet/models/detectors/single_stage.py", line 68, in forward_train
    outs = self.bbox_head(x)
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ai20resch13001/s2anet-b/mmdet/models/anchor_heads_rotated/s2anet_head.py", line 216, in forward
    return multi_apply(self.forward_single, feats, self.anchor_strides)
  File "/home/ai20resch13001/s2anet-b/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/ai20resch13001/s2anet-b/mmdet/models/anchor_heads_rotated/s2anet_head.py", line 195, in forward_single
    self.target_stds)
  File "/home/ai20resch13001/s2anet-b/mmdet/models/anchor_heads_rotated/s2anet_head.py", line 606, in bbox_decode
    anchors, bbox_delta, means, stds, wh_ratio_clip=1e-6)
  File "/home/ai20resch13001/s2anet-b/mmdet/core/bbox/transforms_rotated.py", line 105, in delta2bbox_rotated
    - dy * roi_h * torch.sin(roi_angle) + roi_x
RuntimeError: expected device cuda:1 but got device cuda:0

(s2anet-b) ai20resch13001@iith-4:~/s2anet-b$ CUDA_VISIBLE_DEVICES=1,0,2,3 python tools/train.py /home/ai20resch13001/s2anet-b/configs/dota/s2anet_r50_fpn_1x_dota.py --work_dir /home/ai20resch13001/s2anet-b/work_dirs/ResNet50_fpn_s2anet_1x_dota --gpus 4
2022-05-09 16:31:40,307 - INFO - Distributed training: False
2022-05-09 16:31:40,671 - INFO - load model from: torchvision://resnet50
2022-05-09 16:31:40,885 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

2022-05-09 16:31:42,828 - INFO - Start running, host: ai20resch13001@iith-4, work_dir: /home/ai20resch13001/s2anet-b/work_dirs/ResNet50_fpn_s2anet_1x_dota
2022-05-09 16:31:42,828 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 118, in <module>
    main()
  File "tools/train.py", line 114, in main
    logger=logger)
  File "/home/ai20resch13001/s2anet-b/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/ai20resch13001/s2anet-b/mmdet/apis/train.py", line 232, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/ai20resch13001/s2anet-b/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ai20resch13001/s2anet-b/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/ai20resch13001/s2anet-b/mmdet/models/detectors/base.py", line 100, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/ai20resch13001/s2anet-b/mmdet/models/detectors/single_stage.py", line 68, in forward_train
    outs = self.bbox_head(x)
  File "/home/ai20resch13001/envs/anaconda3/envs/s2anet-b/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ai20resch13001/s2anet-b/mmdet/models/anchor_heads_rotated/s2anet_head.py", line 216, in forward
    return multi_apply(self.forward_single, feats, self.anchor_strides)
  File "/home/ai20resch13001/s2anet-b/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/ai20resch13001/s2anet-b/mmdet/models/anchor_heads_rotated/s2anet_head.py", line 195, in forward_single
    self.target_stds)
  File "/home/ai20resch13001/s2anet-b/mmdet/models/anchor_heads_rotated/s2anet_head.py", line 606, in bbox_decode
    anchors, bbox_delta, means, stds, wh_ratio_clip=1e-6)
  File "/home/ai20resch13001/s2anet-b/mmdet/core/bbox/transforms_rotated.py", line 105, in delta2bbox_rotated
    - dy * roi_h * torch.sin(roi_angle) + roi_x
RuntimeError: expected device cuda:1 but got device cuda:0

Could you kindly let me know what I can do to solve this.

**Comment by csuhan** [comment]
I do not know the exactly reason. Actually, I have not encountered this bug.
I guess the devices of `rois` and `deltas` are different. 
A temporary solution is forcing `deltas` the same device as `rois`: `deltas = deltas.to(rois.device)`.

**Comment by Sairam13001** [comment]
Okay, thank you for the reply.
