### ISSUE TITLE
Hi，does  s2anet support multi anchor_ratios?

### ISSUE THREAD

**Issue by PressEtoRace** [csuhan/s2anet#14]
Hi，when i set "anchor_ratios=[0.5, 2/3, 1.0, 3/2, 2]", there is some error, so how can i set multi anchor_ratios in s2anet?
The error log is:
2020-10-15 14:54:19,828 - INFO - Distributed training: False
2020-10-15 14:54:20,415 - INFO - load model from: torchvision://resnet101
2020-10-15 14:54:20,778 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

2020-10-15 14:54:25,094 - INFO - Start running, host: root@c382926e5c92, work_dir: /user/lsc/workspace/s2anet/work_dirs/match_1015_3
2020-10-15 14:54:25,094 - INFO - workflow: [('train', 1)], max: 36 epochs
Traceback (most recent call last):
  File "tools/train.py", line 109, in <module>
    main()
  File "tools/train.py", line 105, in main
    logger=logger)
  File "/user/lsc/workspace/s2anet/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/user/lsc/workspace/s2anet/mmdet/apis/train.py", line 232, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/root/anaconda3/envs/s2net/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/anaconda3/envs/s2net/lib/python3.6/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/user/lsc/workspace/s2anet/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/root/anaconda3/envs/s2net/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/s2net/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/anaconda3/envs/s2net/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/user/lsc/workspace/s2anet/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/user/lsc/workspace/s2anet/mmdet/models/detectors/base.py", line 100, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/user/lsc/workspace/s2anet/mmdet/models/detectors/s2anet.py", line 66, in forward_train
    outs = self.rbox_head(x)
  File "/root/anaconda3/envs/s2net/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/user/lsc/workspace/s2anet/mmdet/models/anchor_heads/s2anet_head.py", line 369, in forward
    return multi_apply(self.forward_single, feats, self.anchor_strides)
  File "/user/lsc/workspace/s2anet/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/user/lsc/workspace/s2anet/mmdet/models/anchor_heads/s2anet_head.py", line 339, in forward_single
    self.target_stds)
  File "/user/lsc/workspace/s2anet/mmdet/models/anchor_heads/s2anet_head.py", line 45, in bbox_decode
    wh_ratio_clip=1e-6)
  File "/user/lsc/workspace/s2anet/mmdet/core/bbox/transforms_rbox.py", line 70, in delta2rbox
    Rroi_x = (Rrois[:, 0]).unsqueeze(1).expand_as(dx)
RuntimeError: The expanded size of the tensor (16384) must match the existing size (81920) at non-singleton dimension 0.  Target sizes: [16384, 1].  Tensor sizes: [81920, 1]

**Comment by csuhan** [comment]
Hi, @PressEtoRace . Following the trend of anchor-free models, `s2anet` uses one anchor per location in the feature maps, which saves computations and runs faster. So we haven't implemented multiple anchors learning. But it is not impossible to train `s2anet` with multiple anchors. Some methods in [s2anet_head](https://github.com/csuhan/s2anet/blob/master/mmdet/models/anchor_heads/s2anet_head.py) should be modified:
1. `_init_layers`, `forward_single`. You need add multiple anchors like `RetinaNet`. Also, modify `anchor generation`  method and `bbox_decode` method for a batch of anchors. Besides, modify `anchor2offset` in `AlignConv` so that multiple anchors in per location can get multiple `offset` (see [here](https://github.com/csuhan/s2anet/blob/daf71a85264a0aa92639e4493f691427e18fabea/mmdet/models/anchor_heads/s2anet_head.py#L130)).
2. `loss` and `get_refine_anchors`. Modify `get_refine_anchors`, `loss_fam_single` and `loss_odm_single`.
3. `get_bboxes`.

Take `Retinanet` as a reference, it will be not hard if you fully understand [our paper](https://arxiv.org/abs/2008.09397) and mmdetection.

**Comment by jnjhgvjmk** [comment]
Have you implemented multiple scales? @PressEtoRace , Can you share me the model after change? Thank you very much! My e-mail is  1442435009@qq.com

**Comment by LoveDLWujing** [comment]
i just modify the AlignConv to support multi scale and multi ratio anchor setting, it seems to work 
`    def forward(self, x, anchors, stride):
        # TODO: support multi-anchor, anchor_num=1 ==> original
        out = list()
        for i in range(self.anchor_num):
            offset = anchor2offset(anchors[..., i * 5: (i+1) * 5], self.kernel_size, stride)
            out.append(self.relu(self.deform_conv(x, offset)))
        # TODO: max-pooling over multi anchor to get feature
        out = torch.stack(out, dim=1)
        out, _ = torch.max(out, dim=1, keepdim=False)
        return out`
`
        self.fam_reg = nn.Conv2d(self.feat_channels, self.num_anchors * 5, 1)
        self.fam_cls = nn.Conv2d(self.feat_channels, self.num_anchors * self.cls_out_channels, 1)

        self.odm_cls = nn.Conv2d(self.feat_channels, self.num_anchors * self.cls_out_channels, 3, padding=1)
        self.odm_reg = nn.Conv2d(self.feat_channels, self.num_anchors * 5, 3, padding=1)
`

**Comment by taoboyang** [comment]
> i just modified the AlignConv to support multi scale and multi ratio anchor setting, it seems to work
> 
> ```
>     def forward(self, x, anchors, stride):
>         out = list()
>         for i in range(self.anchor_num):
>             offset = anchor2offset(anchors[..., i * 5: (i+1) * 5], self.kernel_size, stride)
>             out.append(self.relu(self.deform_conv(x, offset)))
>         # TODO: max-pooling over multi anchor to get feature
>         out = torch.stack(out, dim=1)
>         out, _ = torch.max(out, dim=1, keepdim=False)
>         return out
> ```
> 
> and modified the `_init_layers`
> 
> ```
> self.fam_reg = nn.Conv2d(self.feat_channels, self.num_anchors * 5, 1)
> self.fam_cls = nn.Conv2d(self.feat_channels, self.num_anchors * self.cls_out_channels, 1)
> 
> self.odm_cls = nn.Conv2d(self.feat_channels, self.num_anchors * self.cls_out_channels, 3, padding=1)
> self.odm_reg = nn.Conv2d(self.feat_channels, self.num_anchors * 5, 3, padding=1)
> ```

Hi I want to know How to set self.anchor_num

**Comment by heyun1994** [comment]
@LoveDLWujing 
Hi，I followed the code you posted with no success. Could you please post all the changed code?
