### ISSUE TITLE
I want to use this project on Cuda 10.2, and during installation the Error displays: 'Error Compiling Objects for extension' . Is your program based on MMCV ==0.2.14 is necessary？ 

### ISSUE THREAD

**Issue by torchsu** [csuhan/s2anet#17]

**Comment by csuhan** [comment]
Actually, we have only tested on cuda 10.0, but others (> 10.0) may also work well.
For mmcv, <=0.2.14 is fine, but >=0.2.15 will encounter errors when training due to the changes of its api.
You may need to check torch's version. s2anet requires torch>=1.3.1.

**Comment by Fly-dream12** [comment]
Error when pip install mmcv=0.2.14
Downloading http://mirrors.aliyun.com/pypi/packages/26/fa/f032c1e0095b4dfac42feae2f4e8ad77dd3ad83257cb5269814c583ac34c/mmcv-0.2.14.tar.gz (48 kB)
     |████████████████████████████████| 48 kB 3.5 MB/s 
    ERROR: Command errored out with exit status 1:
     command: anaconda3/envs/s2anet/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zmxoii56/mmcv/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zmxoii56/mmcv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vlz1eop9
         cwd: /tmp/pip-install-zmxoii56/mmcv/
    Complete output (33 lines):
    WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
    ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
    ERROR: No matching distribution found for pytest-runner
    Traceback (most recent call last):
      File "anaconda3/envs/s2anet/lib/python3.7/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "anaconda3/envs/s2anet/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['anaconda3/envs/s2anet/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpzb366u04', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zmxoii56/mmcv/setup.py", line 83, in <module>
        zip_safe=False)
      File "anaconda3/envs/s2anet/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "anaconda3/envs/s2anet/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "anaconda3/envs/s2anet/lib/python3.7/site-packages/setuptools/dist.py", line 676, in fetch_build_eggs
        replace_conflicting=True,
      File "anaconda3/envs/s2anet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 766, in resolve
        replace_conflicting=replace_conflicting
      File "anaconda3/envs/s2anet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "anaconda3/envs/s2anet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1061, in obtain
        return installer(requirement)
      File "anaconda3/envs/s2anet/lib/python3.7/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "anaconda3/envs/s2anet/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['anaconda3/envs/s2anet/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpzb366u04', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


cuda is 10.0 and torch version is 1.3.1

**Comment by csuhan** [comment]
Please download mmcv and install it in the offline mode.
