### ISSUE TITLE
Something went wrong when I was training my own dataset.

### ISSUE THREAD

**Issue by mosout** [csuhan/s2anet#21]
```
Traceback (most recent call last):
  File "./train.py", line 108, in <module>
    main()
  File "./train.py", line 104, in main
    logger=logger)
  File "/home/spsv/Codes/lph/hjj/s2anet/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/spsv/Codes/lph/hjj/s2anet/mmdet/apis/train.py", line 192, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/spsv/miniconda3/envs/s2anet/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/spsv/miniconda3/envs/s2anet/lib/python3.7/site-packages/mmcv/runner/runner.py", line 274, in train
    self.call_hook('after_train_epoch')
  File "/home/spsv/miniconda3/envs/s2anet/lib/python3.7/site-packages/mmcv/runner/runner.py", line 229, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/spsv/Codes/lph/hjj/s2anet/mmdet/core/evaluation/eval_hooks.py", line 64, in after_train_epoch
    self.evaluate(runner, results)
  File "/home/spsv/Codes/lph/hjj/s2anet/mmdet/core/evaluation/eval_hooks.py", line 92, in evaluate
    bboxes = np.vstack([bboxes, ann['bboxes_ignore']])
  File "<__array_function__ internals>", line 6, in vstack
  File "/home/spsv/miniconda3/envs/s2anet/lib/python3.7/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 0
Traceback (most recent call last):
  File "/home/spsv/miniconda3/envs/s2anet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/spsv/miniconda3/envs/s2anet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/spsv/miniconda3/envs/s2anet/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/spsv/miniconda3/envs/s2anet/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/spsv/miniconda3/envs/s2anet/bin/python', '-u', './train.py', '--local_rank=3', '/home/spsv/Codes/lph/hjj/s2anet/configs/dota/hjj.py', '--launcher', 'pytorch', '--validate']' returned non-zero exit status 1.
```

What should I do to fix this problem?

**Comment by csuhan** [comment]
Please disable validate when training and do validation after training.

**Comment by Miki-lin** [comment]
I train my datasets with this code , but it has some problem with validate. it is no support validate in training?
the map in my datasets is low, so I want to use validate to improve it. what can I do to use the validate?

**Comment by csuhan** [comment]
We have no plan to implement validation after epcoh training.
Please save checkpoints of each epoch and validate it.
