### ISSUE TITLE
python setup.py develop

### ISSUE THREAD

**Issue by why228430** [csuhan/s2anet#34]
when I run "python setup.py develop"  , I meet the error. How I can do to solve the problem!

(s2anet) dl@dl-System-Product-Name:/media/dl/本地磁盘/s2anet$ python setup.py develop
running develop
running egg_info
writing mmdet.egg-info/PKG-INFO
writing dependency_links to mmdet.egg-info/dependency_links.txt
writing requirements to mmdet.egg-info/requires.txt
writing top-level names to mmdet.egg-info/top_level.txt
reading manifest file 'mmdet.egg-info/SOURCES.txt'
writing manifest file 'mmdet.egg-info/SOURCES.txt'
running build_ext
building 'mmdet.ops.nms.soft_nms_cpu' extension
Emitting ninja build file /media/dl/本地磁盘/s2anet/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -shared -B /home/dl/anaconda3/envs/s2anet/compiler_compat -L/home/dl/anaconda3/envs/s2anet/lib -Wl,-rpath=/home/dl/anaconda3/envs/s2anet/lib -Wl,--no-as-needed -Wl,--sysroot=/ /media/dl/本地磁盘/s2anet/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/soft_nms_cpu.o -o build/lib.linux-x86_64-3.7/mmdet/ops/nms/soft_nms_cpu.cpython-37m-x86_64-linux-gnu.so
building 'mmdet.ops.nms.nms_cpu' extension
Emitting ninja build file /media/dl/本地磁盘/s2anet/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -shared -B /home/dl/anaconda3/envs/s2anet/compiler_compat -L/home/dl/anaconda3/envs/s2anet/lib -Wl,-rpath=/home/dl/anaconda3/envs/s2anet/lib -Wl,--no-as-needed -Wl,--sysroot=/ /media/dl/本地磁盘/s2anet/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cpu.o -L/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda-10.2/lib64 - -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/mmdet/ops/nms/nms_cpu.cpython-37m-x86_64-linux-gnu.so
building 'mmdet.ops.nms.nms_cuda' extension
Emitting ninja build file /media/dl/本地磁盘/s2anet/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] c++ -MMD -MF '/media/dl/本地磁盘/s2anet/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o'.d -pthread -B /home/dl/anaconda3/envs/s2anet/compiler_compat -Wl,--sysroot=/ -Wsigmpare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include -I/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/TH -I/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/dl/anaconda3/envs/s2anet/include/python3.7m -c -c '/media/dl/本地磁盘/s2anet/mmdet/ops/nms/src/nms_cuda.cpp' -o '/m/dl/本地磁盘/s2anet/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /media/dl/本地磁盘/s2anet/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o 
c++ -MMD -MF '/media/dl/本地磁盘/s2anet/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o'.d -pthread -B /home/dl/anaconda3/envs/s2anet/compiler_compat -Wl,--sysroot=/ -Wsign-comp-DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include -I/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/TH -I/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/dl/anaconda3/envs/s2anet/include/python3.7m -c -c '/media/dl/本地磁盘/s2anet/mmdet/ops/nms/src/nms_cuda.cpp' -o '/media/d磁盘/s2anet/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /media/dl/本地磁盘/s2anet/mmdet/ops/nms/src/nms_cuda.cpp:2:
/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
/media/dl/本地磁盘/s2anet/mmdet/ops/nms/src/nms_cuda.cpp: In function ‘at::Tensor nms(const at::Tensor&, float)’:
/media/dl/本地磁盘/s2anet/mmdet/ops/nms/src/nms_cuda.cpp:4:39: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tr.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                                       ^
/media/dl/本地磁盘/s2anet/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^~~~~~~~~~
In file included from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3:0,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /media/dl/本地磁盘/s2anet/mmdet/ops/nms/src/nms_cuda.cpp:2:
/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
/media/dl/本地磁盘/s2anet/mmdet/ops/nms/src/nms_cuda.cpp:4:23: error: ‘AT_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
/media/dl/本地磁盘/s2anet/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^~~~~~~~~~
/media/dl/本地磁盘/s2anet/mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: suggested alternative: ‘DCHECK’
 #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                       ^
/media/dl/本地磁盘/s2anet/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
   CHECK_CUDA(dets);
   ^~~~~~~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 228, in <module>
    zip_safe=False)
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
    self.run_command('build_ext')
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/dl/anaconda3/envs/s2anet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by csuhan** [comment]
Try to remove the chinese path and follow our install guide.
Note that s2anet requires torch>=1.3.1 and cuda>=10.0

**Comment by why228430** [comment]
I have removed the chinese path and follow your install guide.
My torch is 1.6.0  and cuda is 10.2
the error  still exists @csuhan

**Comment by csuhan** [comment]
please use torch=1.3.1 and try again

**Comment by YoonaIAN** [comment]
excuse me，do you solve the error?I meet the same error.
