### ISSUE TITLE
undefined symbol: _ZN3c1011CPUTensorIdEv

### ISSUE THREAD

**Issue by wen-flow** [csuhan/s2anet#35]
您好，请问这个问题怎么解决阿， 谢谢：
Traceback (most recent call last):
  File "tools/test.py", line 15, in <module>
    from mmdet.apis import init_dist
  File "/home/wen/Documents/HJJ/s2anet/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/home/wen/Documents/HJJ/s2anet/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/home/wen/Documents/HJJ/s2anet/mmdet/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/wen/Documents/HJJ/s2anet/mmdet/core/anchor/__init__.py", line 2, in <module>
    from .anchor_target import anchor_inside_flags, anchor_target, unmap, images_to_levels
  File "/home/wen/Documents/HJJ/s2anet/mmdet/core/anchor/anchor_target.py", line 3, in <module>
    from ..bbox import PseudoSampler, assign_and_sample, bbox2delta, build_assigner
  File "/home/wen/Documents/HJJ/s2anet/mmdet/core/bbox/__init__.py", line 1, in <module>
    from .assigners import AssignResult, BaseAssigner, MaxIoUAssigner
  File "/home/wen/Documents/HJJ/s2anet/mmdet/core/bbox/assigners/__init__.py", line 1, in <module>
    from .approx_max_iou_assigner import ApproxMaxIoUAssigner
  File "/home/wen/Documents/HJJ/s2anet/mmdet/core/bbox/assigners/approx_max_iou_assigner.py", line 3, in <module>
    from ..geometry import bbox_overlaps
  File "/home/wen/Documents/HJJ/s2anet/mmdet/core/bbox/geometry.py", line 3, in <module>
    from mmdet.ops.box_iou_rotated import box_iou_rotated
  File "/home/wen/Documents/HJJ/s2anet/mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/home/wen/Documents/HJJ/s2anet/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/wen/Documents/HJJ/s2anet/mmdet/ops/dcn/deform_conv.py", line 10, in <module>
    from . import deform_conv_cuda
ImportError: /home/wen/Documents/HJJ/s2anet/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1011CPUTensorIdEv

**Comment by csuhan** [comment]
https://github.com/open-mmlab/mmdetection/issues/592

**Comment by wen-flow** [comment]
Thank you for your replying. I have a question. 
Does the model only need to train 12 epochs according to the configuration file to achieve the result of the paper?

**Comment by csuhan** [comment]
Yes, all models on DOTA (resp. HRSC2016) need to train 12 epochs (resp. 36 epochs).
