### ISSUE TITLE
ImportError: cannot import name 'nms_rotated_cuda' from 'mmdet.ops.nms_rotated' 

### ISSUE THREAD

**Issue by Jnyle** [csuhan/s2anet#48]
hi, it's odd that this error occured when training DOTA for I check the code and seems no problem :

`Traceback (most recent call last):
  File "tools/train.py", line 9, in <module>
    from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
  File "/dat01/zhangshuhao/dy/s2anet-dal/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/dat01/zhangshuhao/dy/s2anet-dal/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/dat01/zhangshuhao/dy/s2anet-dal/mmdet/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/dat01/zhangshuhao/dy/s2anet-dal/mmdet/core/anchor/__init__.py", line 2, in <module>
    from .anchor_target import anchor_inside_flags, anchor_target, unmap, images_to_levels
  File "/dat01/zhangshuhao/dy/s2anet-dal/mmdet/core/anchor/anchor_target.py", line 3, in <module>
    from ..bbox import PseudoSampler, assign_and_sample, bbox2delta, build_assigner
  File "/dat01/zhangshuhao/dy/s2anet-dal/mmdet/core/bbox/__init__.py", line 1, in <module>
    from .assigners import AssignResult, BaseAssigner, MaxIoUAssigner
  File "/dat01/zhangshuhao/dy/s2anet-dal/mmdet/core/bbox/assigners/__init__.py", line 1, in <module>
    from .approx_max_iou_assigner import ApproxMaxIoUAssigner
  File "/dat01/zhangshuhao/dy/s2anet-dal/mmdet/core/bbox/assigners/approx_max_iou_assigner.py", line 3, in <module>
    from ..geometry import bbox_overlaps
  File "/dat01/zhangshuhao/dy/s2anet-dal/mmdet/core/bbox/geometry.py", line 3, in <module>
    from mmdet.ops.box_iou_rotated import box_iou_rotated
  File "/dat01/zhangshuhao/dy/s2anet-dal/mmdet/ops/__init__.py", line 8, in <module>
    from .nms_rotated import nms_rotated
  File "/dat01/zhangshuhao/dy/s2anet-dal/mmdet/ops/nms_rotated/__init__.py", line 1, in <module>
    from . import nms_rotated_cuda
ImportError: cannot import name 'nms_rotated_cuda' from 'mmdet.ops.nms_rotated' (/dat01/zhangshuhao/dy/s2anet-dal/mmdet/ops/nms_rotated/__init__.py)
~`

**Comment by csuhan** [comment]
Please re-run `python setup.py develop` due to the change of our extension name: from `nms_rotated_C` to `nms_rotated_cuda`
https://github.com/csuhan/s2anet/blob/7deb953ff01307dcb3c9156f26b09197f64ec432/setup.py#L213-L216
