### ISSUE TITLE
How do I convert to the onnx model?

### ISSUE THREAD

**Issue by fightli123456** [csuhan/s2anet#51]
I used the script (https://github.com/open-mmlab/mmdetection/tree/master/tools/pytorch2onnx.py) to convert to onnx model and there was an error.

if keep.size(0) > max_num:
/home/admin-123456/s2anet/mys2anet/mmdet/core/bbox/transforms.py:191: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if bboxes.shape[0] == 0:
/home/admin-123456/s2anet/mys2anet/mmdet/core/bbox/transforms.py:196: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  bboxes = bboxes.cpu().numpy()
/home/admin-123456/s2anet/mys2anet/mmdet/core/bbox/transforms.py:197: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  labels = labels.cpu().numpy()
Traceback (most recent call last):
  File "/home/admin-123456/s2anet/mys2anet/pytorch2onnx.py", line 186, in <module>
    test_img=args.test_img)
  File "/home/admin-123456/s2anet/mys2anet/pytorch2onnx.py", line 55, in pytorch2onnx
    opset_version=opset_version)
  File "/home/admin-123456/anaconda3/envs/s2anet-torch1.6/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/admin-123456/anaconda3/envs/s2anet-torch1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/home/admin-123456/anaconda3/envs/s2anet-torch1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/admin-123456/anaconda3/envs/s2anet-torch1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 366, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/admin-123456/anaconda3/envs/s2anet-torch1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 319, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/admin-123456/anaconda3/envs/s2anet-torch1.6/lib/python3.7/site-packages/torch/jit/__init__.py", line 338, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/admin-123456/anaconda3/envs/s2anet-torch1.6/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin-123456/anaconda3/envs/s2anet-torch1.6/lib/python3.7/site-packages/torch/jit/__init__.py", line 426, in forward
    self._force_outplace,
  File "/home/admin-123456/anaconda3/envs/s2anet-torch1.6/lib/python3.7/site-packages/torch/jit/__init__.py", line 415, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type numpy.ndarray

Process finished with exit code 1

**Comment by csuhan** [comment]
For some reasons, converting to onnx may be hard now:
1. The mmdet version of our code is v1.0, while the script you used is for v2.0. As shown in the error log, some funcs have changed in v2.0.
2. We use some additional extensions ,e.g., [orn](https://github.com/csuhan/s2anet/tree/master/mmdet/ops/orn).

**Comment by printfxs** [comment]
Did you succeed?
