### ISSUE TITLE
3090 can only install 11 series of cuda, what should I do?

### ISSUE THREAD

**Issue by lyccol** [csuhan/s2anet#93]
I cannot reproduce the code with the 3090 graphics card. Suspected is the reason for cuda programming.

**Comment by csuhan** [comment]
Please try this https://github.com/csuhan/ReDet/issues/1

**Comment by lyccol** [comment]
Using pip 21.1.2 from /root/anaconda3/envs/s2anet/lib/python3.7/site-packages/pip (python 3.7)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-n58lnl_w
Created temporary directory: /tmp/pip-req-tracker-td4_33n8
Initialized build tracking at /tmp/pip-req-tracker-td4_33n8
Created build tracker: /tmp/pip-req-tracker-td4_33n8
Entered build tracker: /tmp/pip-req-tracker-td4_33n8
Created temporary directory: /tmp/pip-install-xfub3x00
Obtaining file:///root/Documents/s2anet
  Added file:///root/Documents/s2anet to build tracker '/tmp/pip-req-tracker-td4_33n8'
    Running setup.py (path:/root/Documents/s2anet/setup.py) egg_info for package from file:///root/Documents/s2anet
    Created temporary directory: /tmp/pip-pip-egg-info-fg_evk1w
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-fg_evk1w/mmdet.egg-info
    writing /tmp/pip-pip-egg-info-fg_evk1w/mmdet.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-fg_evk1w/mmdet.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-pip-egg-info-fg_evk1w/mmdet.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-fg_evk1w/mmdet.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-fg_evk1w/mmdet.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-fg_evk1w/mmdet.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-pip-egg-info-fg_evk1w/mmdet.egg-info/SOURCES.txt'
  Source in /root/Documents/s2anet has version 1.0rc1+114fafa, which satisfies requirement mmdet==1.0rc1+114fafa from file:///root/Documents/s2anet
  Removed mmdet==1.0rc1+114fafa from file:///root/Documents/s2anet from build tracker '/tmp/pip-req-tracker-td4_33n8'
Requirement already satisfied: cython in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmdet==1.0rc1+114fafa) (0.29.23)
Requirement already satisfied: numpy in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmdet==1.0rc1+114fafa) (1.21.0)
Requirement already satisfied: albumentations in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmdet==1.0rc1+114fafa) (1.0.0)
Requirement already satisfied: imagecorruptions in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmdet==1.0rc1+114fafa) (1.1.2)
Requirement already satisfied: mmcv==0.2.14 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmdet==1.0rc1+114fafa) (0.2.14)
Requirement already satisfied: matplotlib in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmdet==1.0rc1+114fafa) (3.4.2)
Requirement already satisfied: terminaltables in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmdet==1.0rc1+114fafa) (3.1.0)
Requirement already satisfied: six in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmdet==1.0rc1+114fafa) (1.16.0)
Requirement already satisfied: pycocotools in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmdet==1.0rc1+114fafa) (2.0.2)
Requirement already satisfied: pillow==6.2.2 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmdet==1.0rc1+114fafa) (6.2.2)
Requirement already satisfied: shapely in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmdet==1.0rc1+114fafa) (1.7.1)
Requirement already satisfied: requests in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmcv==0.2.14->mmdet==1.0rc1+114fafa) (2.25.1)
Requirement already satisfied: addict in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmcv==0.2.14->mmdet==1.0rc1+114fafa) (2.4.0)
Requirement already satisfied: opencv-python in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmcv==0.2.14->mmdet==1.0rc1+114fafa) (4.5.2.54)
Requirement already satisfied: pyyaml in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from mmcv==0.2.14->mmdet==1.0rc1+114fafa) (5.4.1)
Requirement already satisfied: scikit-image>=0.16.1 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from albumentations->mmdet==1.0rc1+114fafa) (0.18.1)
Requirement already satisfied: scipy in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from albumentations->mmdet==1.0rc1+114fafa) (1.7.0)
Requirement already satisfied: opencv-python-headless>=4.1.1 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from albumentations->mmdet==1.0rc1+114fafa) (4.5.2.54)
Requirement already satisfied: PyWavelets>=1.1.1 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from scikit-image>=0.16.1->albumentations->mmdet==1.0rc1+114fafa) (1.1.1)
Requirement already satisfied: tifffile>=2019.7.26 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from scikit-image>=0.16.1->albumentations->mmdet==1.0rc1+114fafa) (2021.6.14)
Requirement already satisfied: networkx>=2.0 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from scikit-image>=0.16.1->albumentations->mmdet==1.0rc1+114fafa) (2.5.1)
Requirement already satisfied: imageio>=2.3.0 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from scikit-image>=0.16.1->albumentations->mmdet==1.0rc1+114fafa) (2.9.0)
Requirement already satisfied: python-dateutil>=2.7 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from matplotlib->mmdet==1.0rc1+114fafa) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from matplotlib->mmdet==1.0rc1+114fafa) (1.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from matplotlib->mmdet==1.0rc1+114fafa) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from matplotlib->mmdet==1.0rc1+114fafa) (0.10.0)
Requirement already satisfied: decorator<5,>=4.3 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from networkx>=2.0->scikit-image>=0.16.1->albumentations->mmdet==1.0rc1+114fafa) (4.4.2)
Requirement already satisfied: setuptools>=18.0 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from pycocotools->mmdet==1.0rc1+114fafa) (52.0.0.post20210125)
Requirement already satisfied: chardet<5,>=3.0.2 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from requests->mmcv==0.2.14->mmdet==1.0rc1+114fafa) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from requests->mmcv==0.2.14->mmdet==1.0rc1+114fafa) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from requests->mmcv==0.2.14->mmdet==1.0rc1+114fafa) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /root/anaconda3/envs/s2anet/lib/python3.7/site-packages (from requests->mmcv==0.2.14->mmdet==1.0rc1+114fafa) (2021.5.30)
Created temporary directory: /tmp/pip-unpack-iqdyya4u
Installing collected packages: mmdet
  Running setup.py develop for mmdet
    Running command /root/anaconda3/envs/s2anet/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/Documents/s2anet/setup.py'"'"'; __file__='"'"'/root/Documents/s2anet/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing mmdet.egg-info/PKG-INFO
    writing dependency_links to mmdet.egg-info/dependency_links.txt
    writing requirements to mmdet.egg-info/requires.txt
    writing top-level names to mmdet.egg-info/top_level.txt
    reading manifest file 'mmdet.egg-info/SOURCES.txt'
    writing manifest file 'mmdet.egg-info/SOURCES.txt'
    running build_ext
    building 'mmdet.ops.nms.soft_nms_cpu' extension
    Emitting ninja build file /root/Documents/s2anet/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    1.10.2
    g++ -pthread -shared -B /root/anaconda3/envs/s2anet/compiler_compat -L/root/anaconda3/envs/s2anet/lib -Wl,-rpath=/root/anaconda3/envs/s2anet/lib -Wl,--no-as-needed -Wl,--sysroot=/ /root/Documents/s2anet/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/soft_nms_cpu.o -o build/lib.linux-x86_64-3.7/mmdet/ops/nms/soft_nms_cpu.cpython-37m-x86_64-linux-gnu.so
    g++: error: /root/Documents/s2anet/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/soft_nms_cpu.o: No such file or directory
    error: command 'g++' failed with exit status 1
ERROR: Command errored out with exit status 1: /root/anaconda3/envs/s2anet/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/Documents/s2anet/setup.py'"'"'; __file__='"'"'/root/Documents/s2anet/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/root/anaconda3/envs/s2anet/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/root/anaconda3/envs/s2anet/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/root/anaconda3/envs/s2anet/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 402, in run
    pycompile=options.compile,
  File "/root/anaconda3/envs/s2anet/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 85, in install_given_reqs
    pycompile=pycompile,
  File "/root/anaconda3/envs/s2anet/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 787, in install
    unpacked_source_directory=self.unpacked_source_directory,
  File "/root/anaconda3/envs/s2anet/lib/python3.7/site-packages/pip/_internal/operations/install/editable_legacy.py", line 46, in install_editable
    cwd=unpacked_source_directory,
  File "/root/anaconda3/envs/s2anet/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /root/anaconda3/envs/s2anet/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/Documents/s2anet/setup.py'"'"'; __file__='"'"'/root/Documents/s2anet/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-td4_33n8'

**Comment by lyccol** [comment]
running develop
running egg_info
writing mmdet.egg-info/PKG-INFO
writing dependency_links to mmdet.egg-info/dependency_links.txt
writing requirements to mmdet.egg-info/requires.txt
writing top-level names to mmdet.egg-info/top_level.txt
reading manifest file 'mmdet.egg-info/SOURCES.txt'
writing manifest file 'mmdet.egg-info/SOURCES.txt'
running build_ext
building 'mmdet.ops.nms.soft_nms_cpu' extension
Emitting ninja build file /root/Documents/s2anet/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
g++ -pthread -shared -B /root/anaconda3/envs/s2anet/compiler_compat -L/root/anaconda3/envs/s2anet/lib -Wl,-rpath=/root/anaconda3/envs/s2anet/lib -Wl,--no-as-needed -Wl,--sysroot=/ /root/Documents/s2anet/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/soft_nms_cpu.o -o build/lib.linux-x86_64-3.7/mmdet/ops/nms/soft_nms_cpu.cpython-37m-x86_64-linux-gnu.so
g++: error: /root/Documents/s2anet/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/soft_nms_cpu.o: No such file or directory
error: command 'g++' failed with exit status 1

I tried that method, but I still have this problem. This is the error reported by me when there is a problem.

**Comment by lyccol** [comment]
# optional
pip install -r requirements.txt

python setup.py develop
# or "pip install -v -e ."


The error comes from these two commands respectively.
